// Pre-recorded ElevenLabs narration for the Foundations course.
//
// contentId (the act's foundations id) → section id → bundled MP3 module.
// Presence here is the switch: a Foundations act with an entry plays its
// pre-recorded clips; everything else in the app stays on system TTS.
//
// The clips are generated by scripts/generate-foundations-audio.mjs and keyed
// by the section's stable id (NarrativeSection.id), so reordering sections
// can't misalign them. One clip per section; the reader plays them in order
// and turns the page as each finishes.
//
// Only Act 1 ('name') is recorded so far.
export const foundationsAudioManifest: Record<string, Record<string, number>> = {
  name: {
    'f-name-no-founder': require('../../assets/audio/foundations/f-name-no-founder.mp3'),
    'f-name-river': require('../../assets/audio/foundations/f-name-river.mp3'),
    'f-name-sanatana': require('../../assets/audio/foundations/f-name-sanatana.mp3'),
    'f-name-sanskrit': require('../../assets/audio/foundations/f-name-sanskrit.mp3'),
  },
};

// The clip map for a piece of reader content, keyed by section INDEX (in reader
// order), or null when there's no recorded audio for it.
export function prerecordedClipsFor(
  contentType: string,
  contentId: string,
  sectionIds: string[]
): Record<number, number> | null {
  if (contentType !== 'foundations') return null;
  const act = foundationsAudioManifest[contentId];
  if (!act) return null;
  const clips: Record<number, number> = {};
  sectionIds.forEach((sid, i) => {
    if (act[sid]) clips[i] = act[sid];
  });
  return Object.keys(clips).length ? clips : null;
}
