// Pre-recorded ElevenLabs narration for the scripture readers (Ramayana).
//
// kanda id (scripture partId) → section id → bundled MP3 module. Same pipeline
// and switch semantics as the Foundations manifest: presence here means the
// kanda plays its pre-recorded clips (via prerecordedClipsFor); everything else
// stays on system TTS. One clip per section, keyed by the section's stable id
// so reordering can't misalign them.
//
// Clips are generated by scripts/generate-ramayana-audio.mjs with the same Oliver
// voice as Foundations. Bundled → adding/changing clips is a NATIVE build, not OTA.
// Pilot: Bala Kanda (Book 1). The other six kandas follow in later runs.
export const scriptureAudioManifest: Record<string, Record<string, number>> = {
  'bala-kanda': {
    'bala-preface': require('../../assets/audio/ramayana/bala-preface.mp3'),
    'bala-question': require('../../assets/audio/ramayana/bala-question.mp3'),
    'bala-birthless-poem': require('../../assets/audio/ramayana/bala-birthless-poem.mp3'),
    'bala-why-start': require('../../assets/audio/ramayana/bala-why-start.mp3'),
    'bala-term-adikavya': require('../../assets/audio/ramayana/bala-term-adikavya.mp3'),
    'bala-birth': require('../../assets/audio/ramayana/bala-birth.mp3'),
    'bala-blindspot': require('../../assets/audio/ramayana/bala-blindspot.mp3'),
    'bala-vishwamitra': require('../../assets/audio/ramayana/bala-vishwamitra.mp3'),
    'bala-ahalya': require('../../assets/audio/ramayana/bala-ahalya.mp3'),
    'bala-drawn-out': require('../../assets/audio/ramayana/bala-drawn-out.mp3'),
    'bala-term-svayamvara': require('../../assets/audio/ramayana/bala-term-svayamvara.mp3'),
    'bala-bow': require('../../assets/audio/ramayana/bala-bow.mp3'),
    'bala-quiet-power': require('../../assets/audio/ramayana/bala-quiet-power.mp3'),
  },
};
