// Pre-recorded ElevenLabs narration for the scripture readers (Ramayana).
//
// kanda id (scripture partId) → section id → bundled MP3 module. Same pipeline
// and switch semantics as the Foundations manifest: presence here means the
// kanda plays its pre-recorded clips (via prerecordedClipsFor); everything else
// stays on system TTS. One clip per section, keyed by the section's stable id
// so reordering can't misalign them.
//
// Clips are generated by scripts/generate-ramayana-audio.mjs with the same Oliver
// voice as Foundations. Bundled → adding/changing clips is a NATIVE build, not OTA.
// All seven kandas recorded (Bala pilot + the other six, July 2026).
export const scriptureAudioManifest: Record<string, Record<string, number>> = {
  'bala-kanda': {
    'bala-preface': require('../../assets/audio/ramayana/bala-preface.mp3'),
    'bala-question': require('../../assets/audio/ramayana/bala-question.mp3'),
    'bala-birthless-poem': require('../../assets/audio/ramayana/bala-birthless-poem.mp3'),
    'bala-why-start': require('../../assets/audio/ramayana/bala-why-start.mp3'),
    'bala-term-adikavya': require('../../assets/audio/ramayana/bala-term-adikavya.mp3'),
    'bala-ravana': require('../../assets/audio/ramayana/bala-ravana.mp3'),
    'bala-birth': require('../../assets/audio/ramayana/bala-birth.mp3'),
    'bala-blindspot': require('../../assets/audio/ramayana/bala-blindspot.mp3'),
    'bala-vishwamitra': require('../../assets/audio/ramayana/bala-vishwamitra.mp3'),
    'bala-ahalya': require('../../assets/audio/ramayana/bala-ahalya.mp3'),
    'bala-drawn-out': require('../../assets/audio/ramayana/bala-drawn-out.mp3'),
    'bala-term-svayamvara': require('../../assets/audio/ramayana/bala-term-svayamvara.mp3'),
    'bala-bow': require('../../assets/audio/ramayana/bala-bow.mp3'),
    'bala-quiet-power': require('../../assets/audio/ramayana/bala-quiet-power.mp3'),
  },
  'ayodhya-kanda': {
    'ayodhya-where': require('../../assets/audio/ramayana/ayodhya-where.mp3'),
    'ayodhya-eve': require('../../assets/audio/ramayana/ayodhya-eve.mp3'),
    'ayodhya-equanimity': require('../../assets/audio/ramayana/ayodhya-equanimity.mp3'),
    'ayodhya-equanimity-note': require('../../assets/audio/ramayana/ayodhya-equanimity-note.mp3'),
    'ayodhya-term-dharma': require('../../assets/audio/ramayana/ayodhya-term-dharma.mp3'),
    'ayodhya-companions': require('../../assets/audio/ramayana/ayodhya-companions.mp3'),
    'ayodhya-love-note': require('../../assets/audio/ramayana/ayodhya-love-note.mp3'),
    'ayodhya-sandals': require('../../assets/audio/ramayana/ayodhya-sandals.mp3'),
    'ayodhya-power-note': require('../../assets/audio/ramayana/ayodhya-power-note.mp3'),
  },
  'aranya-kanda': {
    'aranya-where': require('../../assets/audio/ramayana/aranya-where.mp3'),
    'aranya-forest': require('../../assets/audio/ramayana/aranya-forest.mp3'),
    'aranya-war-note': require('../../assets/audio/ramayana/aranya-war-note.mp3'),
    'aranya-dharma-embodied': require('../../assets/audio/ramayana/aranya-dharma-embodied.mp3'),
    'aranya-enemy-note': require('../../assets/audio/ramayana/aranya-enemy-note.mp3'),
    'aranya-term-maya': require('../../assets/audio/ramayana/aranya-term-maya.mp3'),
    'aranya-golden-deer': require('../../assets/audio/ramayana/aranya-golden-deer.mp3'),
    'aranya-evil-note': require('../../assets/audio/ramayana/aranya-evil-note.mp3'),
    'aranya-jatayu': require('../../assets/audio/ramayana/aranya-jatayu.mp3'),
    'aranya-fight-note': require('../../assets/audio/ramayana/aranya-fight-note.mp3'),
  },
  'kishkindha-kanda': {
    'kishkindha-where': require('../../assets/audio/ramayana/kishkindha-where.mp3'),
    'kishkindha-meeting': require('../../assets/audio/ramayana/kishkindha-meeting.mp3'),
    'kishkindha-broken-note': require('../../assets/audio/ramayana/kishkindha-broken-note.mp3'),
    'kishkindha-term-vanara': require('../../assets/audio/ramayana/kishkindha-term-vanara.mp3'),
    'kishkindha-vali': require('../../assets/audio/ramayana/kishkindha-vali.mp3'),
    'kishkindha-vali-note': require('../../assets/audio/ramayana/kishkindha-vali-note.mp3'),
    'kishkindha-forgetting': require('../../assets/audio/ramayana/kishkindha-forgetting.mp3'),
    'kishkindha-forgetting-note': require('../../assets/audio/ramayana/kishkindha-forgetting-note.mp3'),
  },
  'sundara-kanda': {
    'sundara-where': require('../../assets/audio/ramayana/sundara-where.mp3'),
    'sundara-leap': require('../../assets/audio/ramayana/sundara-leap.mp3'),
    'sundara-beautiful-note': require('../../assets/audio/ramayana/sundara-beautiful-note.mp3'),
    'sundara-term-bhakti': require('../../assets/audio/ramayana/sundara-term-bhakti.mp3'),
    'sundara-ashoka': require('../../assets/audio/ramayana/sundara-ashoka.mp3'),
    'sundara-captive-note': require('../../assets/audio/ramayana/sundara-captive-note.mp3'),
    'sundara-burning': require('../../assets/audio/ramayana/sundara-burning.mp3'),
    'sundara-pride-note': require('../../assets/audio/ramayana/sundara-pride-note.mp3'),
  },
  'yuddha-kanda': {
    'yuddha-where': require('../../assets/audio/ramayana/yuddha-where.mp3'),
    'yuddha-refuge': require('../../assets/audio/ramayana/yuddha-refuge.mp3'),
    'yuddha-refuge-note': require('../../assets/audio/ramayana/yuddha-refuge-note.mp3'),
    'yuddha-term-sharanagati': require('../../assets/audio/ramayana/yuddha-term-sharanagati.mp3'),
    'yuddha-bridge': require('../../assets/audio/ramayana/yuddha-bridge.mp3'),
    'yuddha-bridge-note': require('../../assets/audio/ramayana/yuddha-bridge-note.mp3'),
    'yuddha-ravana': require('../../assets/audio/ramayana/yuddha-ravana.mp3'),
    'yuddha-ravana-note': require('../../assets/audio/ramayana/yuddha-ravana-note.mp3'),
    'yuddha-return': require('../../assets/audio/ramayana/yuddha-return.mp3'),
    'yuddha-return-note': require('../../assets/audio/ramayana/yuddha-return-note.mp3'),
  },
  'uttara-kanda': {
    'uttara-where': require('../../assets/audio/ramayana/uttara-where.mp3'),
    'uttara-ramarajya': require('../../assets/audio/ramayana/uttara-ramarajya.mp3'),
    'uttara-ramarajya-note': require('../../assets/audio/ramayana/uttara-ramarajya-note.mp3'),
    'uttara-term-ramrajya': require('../../assets/audio/ramayana/uttara-term-ramrajya.mp3'),
    'uttara-banishment': require('../../assets/audio/ramayana/uttara-banishment.mp3'),
    'uttara-banishment-note': require('../../assets/audio/ramayana/uttara-banishment-note.mp3'),
    'uttara-sons': require('../../assets/audio/ramayana/uttara-sons.mp3'),
    'uttara-poem-note': require('../../assets/audio/ramayana/uttara-poem-note.mp3'),
    'uttara-earth': require('../../assets/audio/ramayana/uttara-earth.mp3'),
    'uttara-earth-note': require('../../assets/audio/ramayana/uttara-earth-note.mp3'),
  },
};
